name: test
on:
  push:
    branches:
      # 任何分支
      - '*'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
          cache: true

      - name: Format check
        run: deno task fmt

      - name: Lint
        run: deno task lint

      - name: Type check
        run: deno task check

      - name: Test
        run: deno task test
